[package]
name = "world-parkour"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
rand = { version = "0.8.5", features = ["small_rng"] }
valence = { git = "https://github.com/valence-rs/valence" }
